### ISSUE TITLE
Split components by functionality

### ISSUE THREAD

**Issue by creekorful** [obawi/finance-api#4]
Hello, first of all thanks for your interesting project :)

Here's a little suggestion:

The current architecture looks hard to read / maintain, since all components are defined in a single file.

One of the solution to fix that would be to split the source code into dedicated modules, so that everything is organised by functionality:

```
/routers/
/routers/__init.py__
/routers/transaction.py
/routers/broker.py
/routers/currency.py
/services/
/services/__init.py__
/services/transaction.py
/services/broker.py
/services/currency.py
/repositories/
/repositories/__init.py__
/repositories/transaction.py
/repositories/broker.py
/repositories/currency.py
/__main.py__
[...]
```

And then having a `__main.py__` file that will load modules, register routes, etc..

This follows the project recommendation: https://fastapi.tiangolo.com/tutorial/bigger-applications/

What do you think?

**Comment by obawi** [comment]
Done, thanks for the input
